version: '3.8'
services:
    jenkins-java-example:
      image: objectobjectlady/jenkins-java-example:jje-3.9
      ports:
        - 8080:8080
    postgres:
      image: postgres:13
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=my-pwd
